package com.yu.xbox

package object currency {
  val CountryCurrencyMap: Map[String, String] = Map(
    "AT" -> "EUR",
    "BE" -> "EUR",
    "DE" -> "EUR",
    "ES" -> "EUR",
    "FI" -> "EUR",
    "FR" -> "EUR",
    "GR" -> "EUR",
    "PT" -> "EUR",
    "IE" -> "EUR",
    "IT" -> "EUR",
    "NL" -> "EUR",
    "SK" -> "EUR",
    "AE" -> "USD",
    "US" -> "USD",
    "AR" -> "ARS",
    "AU" -> "AUD",
    "BR" -> "BRL",
    "CA" -> "CAD",
    "CH" -> "CHF",
    "CL" -> "CLP",
    "CO" -> "COP",
    "CZ" -> "CZK",
    "DK" -> "DKK",
    "GB" -> "GBP",
    "HK" -> "HKD",
    "HU" -> "HUF",
    "IL" -> "ILS",
    "IN" -> "INR",
    "JP" -> "JPY",
    "KR" -> "KRW",
    "MX" -> "MXN",
    "NO" -> "NOK",
    "NZ" -> "NZD",
    "PL" -> "PLN",
    "SA" -> "SAR",
    "SE" -> "SEK",
    "SG" -> "SGD",
    "TR" -> "TRY",
    "TW" -> "TWD",
    "ZA" -> "ZAR",
    "RU" -> ""
  )
}
